# Generated by Django 3.1.7 on 2023-04-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField()),
                ('age', models.IntegerField()),
                ('country', models.TextField()),
                ('phone', models.TextField(blank=True)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
